sudo: required
dist: trusty

services:
  - docker
branches:
    only:
      - master

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.scripts/repo-sync.sh; fi'
  # Commit changes unless pull request
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.scripts/repo-sync.sh true; fi'
